name: UI automation tests
on:

  workflow_dispatch:
   inputs:
      target:
        description: "Environment against which the tests will run"
        required: false
        type: choice
        options:
          - dev
          - demo
        default: dev
jobs:
  ui-tests:
    name: UI automation tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      issues: read
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: install playwright browsers
        run: npx playwright install --with-deps
      - name: Run test cases
        run: npm run test
      - name: Save Allure Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Allure Report
          path: |
            allure-results/
      - name: Publish Test Report
        uses: EnricoMi/publish-unit-test-result-action/composite@v1
        if: always()
        with:
          files: "junit.xml"
          comment_mode: off
